bots:
  - host: localhost
    name: MyInternalBotName
    nick: HyRC
    debug-output:
      exceptions: false
      input: false
      output: false
endpoints:
  - name: Chat
    type: hy-chat
  - name: Join
    type: hy-join
  - name: Quit
    type: hy-quit
  - name: IRC
    type: irc
    extra:
      bot: MyInternalBotName
      channel: "#HyRC"
links:
  - source: Chat
    target: IRC
  - source: IRC
    target: Chat
    filters:
      - type: datamapper
        message: "[IRC] <%IRC_PREFIX%%SENDER_NAME%> %MESSAGE_TEXT%"
  - source: Join
    target: IRC
  - source: Quit
    target: IRC
